### ISSUE TITLE
schedule container not sliding

### ISSUE THREAD

**Issue by shubham3211** [agbilotia1998/FE-Scheduler#1]
open directly
![slide](https://user-images.githubusercontent.com/19900978/41843955-6d7f1f00-788c-11e8-9d6d-0a1423091a5e.png)
open-event-webapp (Slide and open)
![slide1](https://user-images.githubusercontent.com/19900978/41843962-719c7560-788c-11e8-8b9d-135acd650638.png)

**Comment by agbilotia1998** [comment]
Please give screenshots or GIFs.

**Comment by agbilotia1998** [comment]
Fixed with https://github.com/agbilotia1998/FE-Scheduler/commit/6f6617b928f8821640df0c8431a7e44d32dcc234
