### ISSUE TITLE
image too big

### ISSUE THREAD

**Issue by shubham3211** [agbilotia1998/FE-Scheduler#2]
![img1](https://user-images.githubusercontent.com/19900978/41843409-1a289102-788b-11e8-81bf-a05448d66d79.png)
Open-event-webapp
![11](https://user-images.githubusercontent.com/19900978/41843427-23fe8f24-788b-11e8-805e-bfc7b6111985.png)

**Comment by agbilotia1998** [comment]
@shubham3211 please provide the screenshot.

**Comment by agbilotia1998** [comment]
Fixed with https://github.com/agbilotia1998/FE-Scheduler/commit/6f6617b928f8821640df0c8431a7e44d32dcc234
