### ISSUE TITLE
increase margin of hr

### ISSUE THREAD

**Issue by shubham3211** [agbilotia1998/FE-Scheduler#4]
![margin](https://user-images.githubusercontent.com/19900978/41843681-c7e49638-788b-11e8-8293-979176afb79b.png)
open-event-webapp
![margin2](https://user-images.githubusercontent.com/19900978/41843687-cbec7b6a-788b-11e8-9c5b-f776a7fd91d5.png)

**Comment by agbilotia1998** [comment]
@shubham3211 please provide the screenshot.

**Comment by agbilotia1998** [comment]
Fixed with https://github.com/agbilotia1998/FE-Scheduler/commit/6f6617b928f8821640df0c8431a7e44d32dcc234
