### ISSUE TITLE
see the pic

### ISSUE THREAD

**Issue by shubham3211** [agbilotia1998/FE-Scheduler#6]
![error](https://user-images.githubusercontent.com/19900978/41792292-ffabec00-7675-11e8-9a13-f96f01daacb3.png)

**Comment by agbilotia1998** [comment]
This is the default avatar image.

**Comment by shubham3211** [comment]
I meant the pic i uploaded , schedule should open on the next line

**Comment by agbilotia1998** [comment]
It is meant to be like this I guess and similar to web app.
