### ISSUE TITLE
change color of calendar icon and download icon

### ISSUE THREAD

**Issue by shubham3211** [agbilotia1998/FE-Scheduler#8]
![icon](https://user-images.githubusercontent.com/19900978/41843593-89e87c5a-788b-11e8-85ab-deb13b7d8663.png)
open-event-webapp
![icon1](https://user-images.githubusercontent.com/19900978/41843607-908bd4a8-788b-11e8-8210-5bb9eff74d30.png)

**Comment by agbilotia1998** [comment]
Please give screenshots or GIFs.

**Comment by agbilotia1998** [comment]
Ummm I guess that can depend on the frontend design, we can change it later.
